#!/usr/bin/env python3
"""
Convert browser-extension JSON cookies (Firefox/Chrome export) to Netscape cookies.txt
Usage: python3 scripts/convert_cookies.py <input.json> [output.txt]
"""
import json
import sys


def convert(input_path: str, output_path: str, domain_filter: str = None):
    with open(input_path, "r", encoding="utf-8") as f:
        raw = f.read().strip()

    # Tolerate BOM / leading garbage
    start = raw.find("[")
    end = raw.rfind("]")
    if start == -1 or end == -1:
        print("ERROR: input does not look like a JSON array")
        sys.exit(1)
    data = json.loads(raw[start:end + 1])

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by convert_cookies.py from browser-extension JSON export",
        "",
    ]
    seen = set()
    count = 0
    for c in data:
        name = c.get("name", "")
        domain = c.get("domain", "")
        if not name or not domain:
            continue
        if domain_filter and domain_filter not in domain:
            continue

        path = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        if c.get("session") or not c.get("expirationDate"):
            expires = "0"
        else:
            expires = str(int(c["expirationDate"]))
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"

        key = (domain, path, name)
        if key in seen:
            continue  # dedupe (firefox storeIds / partitions)
        seen.add(key)

        value = str(c.get("value", ""))
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
        count += 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"OK: wrote {count} cookies -> {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    inp = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "cookies.txt"
    dom = sys.argv[3] if len(sys.argv) > 3 else None
    convert(inp, out, dom)
